spring:
  application:
    name: "training-restapi"
  datasource:
    url: jdbc:h2:mem:mytestdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

training-restapi:
  openapi:
    dev-url: "http://localhost:8080"
    prod-url: "https://www.production.com"